name: naijasocial
description: A naija social chat app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2
  animations: ^2.0.3
  animated_text_kit: ^4.2.2
  curved_navigation_bar: ^1.0.3
  flutter_settings_ui: ^2.0.1
  cached_network_image: ^3.2.1
  provider: ^6.0.3
  google_sign_in: 5.4.1
  firebase_analytics: ^9.3.2
  firebase_auth: ^3.6.4
  firebase_database: ^9.1.2
  firebase_storage: ^10.3.6
  cloud_firestore: ^3.1.0
  emoji_picker_flutter: ^1.0.7
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.1.0
  fluttericon: ^2.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  page_transition: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - images/
